### PR TITLE
Encryption module #1

### PR DESCRIPTION
**Pull request by kiryteo**
Java file to encrypt text to morse.

### CODE REVIEW

**Review by DigantaD — COMMENTED** [review]
The encryption module isn't giving the expected output. 
Eg: If my input is : DD364 , the output should be : _.. _.. ...__ ...._
Instead, it's showing as : ...__ _.... ...._
Please ensure that you get the correct encryption.
Also, I would recommend you to use the JAVA Collections Framework i.e. Hashmaps/Hashtables for this . You could refer to the file in this repository: MorseCodeDecryption.java

**Comment by kiryteo** [comment]
Sure.. I'll look into this asap.

**Comment by kiryteo** [comment]
I tried running MorseCodeDecryption.java, it compiles but not giving the required output i.e. gives empty string as output.. Should I open this as an issue.?

**Comment by DigantaD** [comment]
It was running properly when I had made the commit... Anyway, make it an
issue.
Also, I will look into the code again.

**Pull request closed without merging**
